recipes/recipe_app/urls.py
from django.conf.urls import url

from recipe_app.views import home, favorites, toprated, myrecipes, contact, about, recipe_detail, recipe_update, recipe_delete

from recipe_app.views_create_account import createaccount
from recipe_app.views_login import user_login
from recipe_app.views_logout import user_logout
from recipe_app.views_addrecipe import addrecipe

urlpatterns = [
    url(r'^home/$', home, name='home'),
    url(r'^recipe_detail/(?P<id>\d+)/$', recipe_detail, name='detail'),
    url(r'^recipe_edit/(?P<pk>\d+)/$', recipe_update, name='update'),
    url(r'^recipe_delete/(?P<id>\d+)/$', recipe_delete, name='delete'),
    url(r'^favorites/', favorites, name='favorites'),
    url(r'^toprated/', toprated, name='toprated'),
    url(r'^myrecipes/', myrecipes, name='myrecipes'),
    #url(r'^addrecipe/', addrecipe, name='addrecipe'),
    url(r'^addrecipe/(?P<recipe_pk>.*)/$', addrecipe, name='addrecipe'),
    url(r'^createaccount/', createaccount, name='createaccount'),
    url(r'^contact/', contact, name='contact'),
    url(r'^about/', about, name='about'),
    url(r'^login/', user_login, name='login'),
    url(r'^logout/', user_logout, name='logout'),
]

recipes/recipe_app/models.py
from __future__ import unicode_literals

from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.core.urlresolvers import reverse
from django.db import models

from star_ratings.models import Rating



RATING_VALUES = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5))


MEASUREMENTUNIT_CHOICES = (('dash', 'dash'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('fl oz', 'fl oz'), ('cup', 'cup'),
                           ('pint', 'pint'), ('quart', 'quart'), ('ml', 'ml'), ('cc', 'cc'), ('liter', 'liter'),
                           ('lb', 'lb'), ('oz', 'oz'), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('pieces', 'pieces'),
                           ('whole', 'whole'), ('slice', 'slice')
                           )



class MealType(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return "{}".format(self.name)


class Recipe(models.Model):
    recipe_name = models.CharField(max_length=255)
    description = models.TextField(null=True)
    meal_type = models.ForeignKey(MealType)
    directions = models.TextField()
    author = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    ratings = GenericRelation(Rating)

    def __unicode__(self):
        return "Recipe: {}, description: {}, meal_type: {}, directions: {}, id: {}"\
            .format(self.recipe_name, self.description, self.meal_type, self.directions, self.id)

    def get_absolute_url(self):
        return reverse("recipes:detail", kwargs={'id': self.id})

    def get_rating(self):
        if not self.rating_set.count():
            return "No ratings for {}" .format(self.recipe_name)
        total = 0
        for rate in self.rating_set.all():
            total += rate.rating
        return total / self.rating_set.count()


class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe)
    ingredient_name = models.CharField(max_length=255)
    quantity = models.FloatField(max_length=10)
    measurement_unit = models.CharField(max_length=100, choices=MEASUREMENTUNIT_CHOICES, null=True)

    def __unicode__(self):
        return "{} {} {} - {} ".format(self.quantity, self.measurement_unit, self.ingredient_name, self.recipe.recipe_name)



"""
class RecipeRating(models.Model):

    class Meta:
        unique_together = (('recipe_r_name', 'author'))

    recipe_r_name = models.ForeignKey(Recipe)
    rating = models.FloatField(choices=RATING_VALUES, null=True)
    author = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


    def __unicode__(self):
        return "Recipe Name: {}, Recipe Rating: {}, Recipe Author: {}" .format(self.recipe_r_name, self.rating, self.author)
"""


class UserProfile(models.Model):
    if __name__ == '__main__':
        user = models.OneToOneField(User)  #Required-links UserProfile to a User model instance

        #The additional attributes we wish to include:
        #picture = models.ImageField(upload_to='profile_images', blank=True)

        def __unicode__(self):
            return self.user



class Favorite(models.Model):
    fav_recipe = models.ManyToManyField(Recipe)
    fav_user = models.ManyToManyField(User)

    def __str__(self):
            return "recipe: {}, user: {}".format(self.fav_recipe, self.fav_user)

recipes/recipe_app/templates/about.html
{% extends "layout.html" %}

{% block title %}About Baller Recipes{% endblock %}


    {% block content %}

</br></br></br></br></br></br>

<p> Baller Recipes was created as a class project for an entry level Python class through
<a href="http://www.davincicoders.com/">Davinci Coders</a>.  My wife has always told me that she wished she could
search recipes based on ingredients we had at the house.  It seemed like as good a project as any when I had to pick a
topic.  Prior to starting the 12 week Python course, I had no experience with computer programming.  This projects was
started week 7.

    {% endblock %}

recipes/recipe_app/templates/addrecipe.html
{% extends "layout.html" %}

{% block title %}Create Recipe{% endblock %}

  {% block content %}

</br></br></br>

    <form method="post" action="">
    Recipe Name: {{ recipe_form.recipe_name }} </p>
    {{ ingredient_form.management_form }}
    {% for form in ingredient_form %}
        {{ form.as_table }} </p>
    {% endfor %} </p>
      {% csrf_token %}
    <input type="submit" value="Add Ingredient" name="add_ingredient"/> </p>


    Description: {{ recipe_form.description }} </p>
    Meal Type: {{ recipe_form.meal_type }} </p>
    Directions: {{ recipe_form.directions }} </p>

    <input type="submit" value="Add Recipe" name="submit"/>


    </form>


    {% endblock %}}

recipes/recipe_app/templates/contact.html
{% extends "layout.html" %}

{% block title %}Contact Us{% endblock %}

{% block content %}

</br></br></br>
    <form>
        <form role="form" action="" method="post"
        {% csrf_token %}
        {{ contact_form.as_p }}

            <input type="submit" value="Send Message" />


    </form>

{% endblock %}

recipes/recipe_app/templates/createaccount.html
<!DOCTYPE html>
<html>
    <head>
        <title>Create Account</title>
    </head>

    <body>
        <h1>Create your Baller Recipes Account!</h1>

    {% if registered %}
    Baller Recipes says: <strong>thank you for registering!</strong>
    <a href="{% url 'recipes:home' %}">Return to the homepage.</a><br />
    {% else %}
    <strong>Register Here!</strong><br />

    <form id="user_form" method="post" action="recipe_app/createaccount"
          enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Display each form.  The as_p method wraps each element in a paragraph (<p>) element.
        This ensures each element appears on a new line, making everything look neater. -->
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <!-- Provide a button to click to submit the form. -->
        <input type="submit" name="submit" value="Register"  />
    </form>
    {% endif %}

    </body>
</html>

recipes/recipe_app/templates/favorites.html
{% extends "layout.html" %}

{% block title %}My Favorite Recipes{% endblock %}

  {% block content %}

</br></br></br>

    {% if count != null %}

        <p>There {% if count == 1 %} is {% endif %} {% if count != 1 %} are {% endif %} {{ count }}
            recipe{{ count|pluralize }} in your favorites list</p>

    {% for obj in favorites_list %}

        <br/>

        <a href="{{ obj.get_absolute_url }}">  <h4> {{ obj.fav_recipe.recipe_name }} </h4> </a>
        &nbsp;&nbsp;&nbsp;&nbsp; {{ obj.meal_type }} <br/>
        &nbsp;&nbsp;&nbsp;&nbsp; {{ obj.fav_recipe.description }} <br/>

    {% endfor %}

    {% endif %}

        {% endblock %}

recipes/recipe_app/templates/home.html
{% extends "layout.html" %}

{% block title %}Baller Recipes{% endblock %}

{% load ratings %}

    {% block content %}

              <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h2>An edible maelstrom of organic debris</h2>
        <p>brings a whole new meaning to Awesome Possum!</p>
      </div>


      <div class="container">
         <h3>What types of meal(s) are you looking for?</h3>



          <div>
          <form action="" method="GET" class="multiselect">
            <label class="checkbox-inline">
                <input type="checkbox" checked="true" name="mealtype" value="Breakfast">Breakfast
            </label>
            <label class="checkbox-inline">
                <input type="checkbox" checked="true" name="mealtype" value="Lunch">Lunch
            </label>
            <label class="checkbox-inline">
                <input type="checkbox" checked="true" name="mealtype" value="Dinner">Dinner
            </label>
            <br>
            <label class="checkbox-inline">
                <input type="checkbox" checked="true" name="mealtype" value="Appetizer">Appetizer
            </label>
            <label class="checkbox-inline">
                <input type="checkbox" checked="true" name="mealtype" value="Side_Dish">Side Dish
            </label>
            <label class="checkbox-inline">
                <input type="checkbox" checked="true" name="mealtype" value="Dessert">Dessert
            </label>
            </br>

              <input type="text" name='q' placeholder="Recipe Name or Ingredients here" />
              <input id=search_recipe_form type="submit" value="Search Recipes!" />
          </form>
      </div>

        {% if count != null %}

        <p>There {% if count == 1 %} is {% endif %} {% if count != 1 %} are {% endif %} {{ count }}
            recipe{{ count|pluralize }} matching your search</p>

        {% for obj in queryset_results %}

        <br/>
        <!-- {% url "recipes:detail" id=obj.id %} -->
        <a href="{{ obj.get_absolute_url }}">  <h4> {{ obj.recipe_name }} </h4> </a>
        &nbsp;&nbsp;&nbsp;&nbsp; {{ obj.meal_type }} <br/>
        &nbsp;&nbsp;&nbsp;&nbsp; {{ obj.description }} <br/>

        {% endfor %}

        {% endif %}

        {% endblock %}

recipes/recipe_app/templates/layout.html
{% load static from staticfiles %}
{%

<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

        <title>{% block title %}{% endblock %}</title>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

        <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    <link href="theme.css" rel="stylesheet">

      <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!--Would like to add Awesome Bootstrap Checkbox for checkbox styling -->

        {% load static %}
<html>
...
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
...
</html>

    </head>
    <body>

         <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'recipes:home' %}">Baller Recipes</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><li><a href="{% url 'recipes:about' %}">About</a></li></li>
            <li><a href="{% url 'recipes:contact' %}">Contact</a></li>
            <li><a href="{% url 'recipes:toprated' %}">Top Rated Recipes</a></li>

            {% if user.is_authenticated %}

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/recipe_app/">My Account</a></li>
                <li><a href="{% url 'recipes:favorites' %}">My Favorite Recipes</a></li>
                <li><a href="{% url 'recipes:myrecipes' %}">Recipes I've Created</a></li>
                <li><a href="{% url 'recipes:addrecipe' recipe_pk %}">Create Recipe</a></li>
                <li><a href="{% url 'recipes:logout' %}">Log Out</a></li>
              </ul>
            </li>


            {% else %}
            <li><a href="{% url 'recipes:createaccount' %}">Create Account</a></li>
            <li><a href="{% url 'recipes:login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">




    {% block content %}{% endblock %}</body>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>

recipes/recipe_app/templates/myrecipes.html
{% extends "layout.html" %}

{% block title %}Recipes I've created{% endblock %}

  {% block content %}

</br></br></br>

    {% if count == null %}
    You have not created any recipes yet <br/>
    <a href="{% url 'recipes:addrecipe' %}">Create One Here</a
        {% endif %}

    {% if count != null %}

        <p>You have created {{ count }} recipe{{ count|pluralize }}! </p>
        <p>Great Job! </p>

    {% for obj in myrecipes_list %}

        <br/>

        <a href="{{ obj.get_absolute_url }}">  <h4> {{ obj.recipe_name }} </h4> </a>
        &nbsp;&nbsp;&nbsp;&nbsp; {{ obj.meal_type }} <br/>
        &nbsp;&nbsp;&nbsp;&nbsp; {{ obj.description }} <br/>

    {% endfor %}

    {% endif %}

        {% endblock %}

recipes/recipe_app/templates/recipe_detail.html
{% extends "layout.html" %}

{% block title %}Baller Recipes{% endblock %}

{% block content %}

</br></br></br>


        {% load ratings %}
        {% ratings rec %}


        <form method="POST" action="">
        <button type="submit" name="favorite" class="btn btn-success">
            Favorite this Recipe </button>
        {% csrf_token %}
        </form>

        <h1> {{ rec.recipe_name }} </h1> <br/>
        Description: {{ rec.description}}<br/><br/>
        Meal Type: {{ rec.meal_type }}<br/><br/>


        Ingredients: <br/>
        {% for ings in rec.ingredient_set.all %}
        {{ ings.quantity }}
        {{ ings.measurement_unit }}
        {{ ings.ingredient_name }}<br/>
        {% endfor %}<br/>

        Directions: {{ rec.directions }}<br/><br/>
        Created By: {{ rec.author }}<br/><br/>
        Created On: {{ rec.created }}<br/><br/>
        Last Modified: {{ rec.modified }}<br/><br/>

        {% if rec.author.pk == request.user.pk %}
        <a class="btn btn-warning" href="{% url 'recipes:update' pk=rec.pk %}" type="button"
                 role="button">Edit Recipe</a>
        {% endif %}


{% endblock %}

recipes/recipe_app/templates/signin.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

recipes/recipe_app/templates/toprated.html
{% extends "layout.html" %}

{% block title %}Top Rated Recipes{% endblock %}


    {% block content %}

</br></br></br>

        <h2>Top Rated Recipes:</h2>

        {% for obj in queryset_results %}

        <br/>

        <a href="{{ obj.get_absolute_url }}">  <h4> {{ obj.recipe_name }} </h4> </a>
        &nbsp;&nbsp;&nbsp;&nbsp; {{ obj.meal_type }} <br/>
        &nbsp;&nbsp;&nbsp;&nbsp; {{ obj.description }} <br/>

        {% endfor %}



    {% endblock %}